// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rosmium_run
Rcpp::List rosmium_run(std::string command, std::vector<std::string> args);
RcppExport SEXP _rosmium_rosmium_run(SEXP commandSEXP, SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type command(commandSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(rosmium_run(command, args));
    return rcpp_result_gen;
END_RCPP
}
// rosmium_registered_commands
Rcpp::CharacterVector rosmium_registered_commands();
RcppExport SEXP _rosmium_rosmium_registered_commands() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rosmium_registered_commands());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rosmium_rosmium_run", (DL_FUNC) &_rosmium_rosmium_run, 2},
    {"_rosmium_rosmium_registered_commands", (DL_FUNC) &_rosmium_rosmium_registered_commands, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rosmium(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
