# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run an osmium-tool command in-process
#'
#' Internal bridge to the vendored osmium-tool Command classes. Not
#' intended to be called directly by package users; see the per-command
#' wrapper functions (osmium_cat(), osmium_extract(), ...) instead.
#'
#' @param command Command name, e.g. "cat", "extract", "fileinfo".
#' @param args Character vector of command-line-style arguments, in the
#'   same shape as the corresponding `osmium <command> ...` invocation
#'   (without the leading command name).
#' @return A list with elements ok (logical), ran (logical, whether run()
#'   was reached at all), error (string or NULL), stdout (string), stderr
#'   (string).
osmiumr_run <- function(command, args) {
    .Call(`_osmiumr_osmiumr_run`, command, args)
}

#' List commands registered with the vendored osmium-tool CommandFactory
#' @return character vector of command names
osmiumr_registered_commands <- function() {
    .Call(`_osmiumr_osmiumr_registered_commands`)
}

